branch-defaults:
  ib-locustfile-changes-new:
    environment: locust-dev
global:
  application_name: Locust
  branch: null
  default_ec2_keyname: mit-staging
  default_platform: Python 2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
